name: Biome Flatlands
main: com.gmail.nixillumbreon.BiomeFlatlands.BiomeFlatlands
version: Beta 1.0 build 1
author: NixillUmbreon
description: A plugin that generates biome-compliant flat worlds.
load: STARTUP